title:        MODULUS
tagline:      'Modulus Open Source'
description:  "The home of Modulus' open source projects."
url:          http://onmodulus.github.io
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
highlighter:  pygments
paginate:     5
